looper/urls.py
from django.urls import path

from .views import checkout, settings, preferred_currency

app_name = 'looper'
urlpatterns = [
    path('checkout/<int:plan_id>',
         checkout.ChooseDefaultPlanVariationView.as_view(), name='checkout_new'),
    path('checkout/<int:plan_id>/choose/<int:current_plan_variation_id>',
         checkout.ChoosePlanVariationView.as_view(), name='checkout_choose_plan_variation'),
    path('checkout/<int:plan_id>/variation/<int:plan_variation_id>',
         checkout.CheckoutView.as_view(), name='checkout'),
    path('checkout/pay/<int:order_id>',
         checkout.CheckoutExistingOrderView.as_view(), name='checkout_existing_order'),
    path('checkout/done/<int:transaction_id>', checkout.DoneView.as_view(), name='checkout_done'),
    path('checkout/<gateway_name>/<int:pk>',
         checkout.TransactionlessCheckoutDoneView.as_view(),
         name='transactionless_checkout_done'),

    path('settings/billing/', settings.BillingAddressView.as_view(), name='settings_billing_info'),
    path('settings/personal/', settings.PersonalInfoView.as_view(), name='settings_personal_info'),
    path('settings/billing/payment-methods/',
         settings.PaymentMethodsView.as_view(),
         name='payment_methods'),
    path('settings/billing/payment-methods/change/<int:subscription_id>',
         settings.PaymentMethodChangeView.as_view(),
         name='payment_method_change'),
    path('settings/billing/payment-methods/replace/<int:pk>',
         settings.PaymentMethodReplaceView.as_view(),
         name='payment_method_replace'),
    path('settings/billing/payment-methods/delete/<int:pk>',
         settings.PaymentMethodDeleteView.as_view(),
         name='payment_method_delete'),

    # Note: this URL is used hardcodedly in websrc/scripts/tutti/02_currency.js
    path('preferred-currency', preferred_currency.CurrencySelectorView.as_view(),
         name='preferred_currency'),
]

looper/forms.py
import logging
import typing

from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
import django.contrib.auth.forms as auth_forms

from . import exceptions, models, model_mixins, money, form_fields

log = logging.getLogger(__name__)


class BlenderClassesFormMixin:
    """Adds the CSS classes we need to Django forms."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = f'field-{field_name}'

    def __getitem__(self, field_name: str):
        """Ugly hack to get custom CSS classes in the row container element.

        This will break when Django changes its internal structure.
        """
        from django.forms import BoundField

        # BaseForm._html_output() uses `self[field_name]` to obtain the bound field.
        # To hook into that. we override __getitem__().
        bound_field = super().__getitem__(field_name)  # type: ignore
        if not isinstance(bound_field, BoundField):
            return bound_field

        # `bound_field.css_classes()` is used by BaseForm._html_output() to obtain the
        # CSS classes that are used by the <li> element (when using form.as_ul()).
        # Fortunately it accepts extra CSS classes, but unfortunately we cannot pass
        # anything to the call. Instead, we replace that function with our own, and
        # inject the extra classes there.
        orig_css_classes = bound_field.css_classes

        def css_classes(extra_class: typing.Optional[str] = None) -> str:
            widget_classes: str = bound_field.field.widget.attrs.get('class', '')
            if extra_class:
                widget_classes = f'{widget_classes} {extra_class}'
            return orig_css_classes(widget_classes)

        bound_field.css_classes = css_classes
        return bound_field


class AddressForm(BlenderClassesFormMixin, forms.ModelForm):
    class Meta:
        model = models.Address
        exclude = ['category', 'user']


class BasePaymentForm(forms.Form):
    payment_method_nonce = forms.CharField(initial='set-in-javascript', widget=forms.HiddenInput())
    gateway = form_fields.GatewayChoiceField()


class BaseCheckoutForm(BasePaymentForm):
    # These are used when a payment fails, so that the next attempt to pay can reuse
    # the already-created subscription and order.
    subscription_pk = forms.CharField(widget=forms.HiddenInput(), required=False)
    order_pk = forms.CharField(widget=forms.HiddenInput(), required=False)


class CheckoutForm(BaseCheckoutForm, AddressForm):
    class Meta(AddressForm.Meta):
        pass


class PaymentMethodReplaceForm(BasePaymentForm):
    pass


class ChangePaymentMethodForm(BasePaymentForm):
    next_url_after_done = forms.CharField(widget=forms.HiddenInput())


class CustomerForm(BlenderClassesFormMixin, forms.ModelForm):
    class Meta:
        model = models.Customer
        exclude = ['user', 'vat_number', 'tax_exempt']


class StateMachineMixin(forms.ModelForm):
    """Mix-in for forms that handle looper.model_mixins.StateMachineMixin objects."""

    def clean_status(self):
        assert isinstance(self.instance, model_mixins.StateMachineMixin)

        old_status = self.instance.status
        new_status = self.cleaned_data['status']
        if old_status == new_status:
            # Always accept the current status.
            return new_status

        if not self.instance.may_transition_to(new_status):
            raise ValidationError(f'Status transition {old_status.title()} → '
                                  f'{new_status.title()} is not allowed.')
        return new_status


class PaymentMethodLimitMixin(forms.ModelForm):

    def __init__(self, *args, instance: typing.Optional[models.Subscription] = None, **kwargs) \
            -> None:
        if not instance:
            # When there is no instance, we don't know whose payment methods to list,
            # so it's better to not list them at all.
            invalid_user_id = -1
            queryset = models.PaymentMethod.objects.filter(user_id=invalid_user_id)
        else:
            queryset = instance.user.paymentmethod_set
        self.base_fields['payment_method'].queryset = queryset
        super().__init__(*args, instance=instance, **kwargs)


class SubscriptionAdminForm(StateMachineMixin, PaymentMethodLimitMixin, forms.ModelForm):
    class Meta:
        model = models.Subscription
        exclude = ['id']

    def clean_collection_method(self) -> str:
        payment_method = self.cleaned_data['payment_method']
        collection_method = self.cleaned_data['collection_method']

        if self.instance.collection_method != collection_method and \
                'managed' in {self.instance.collection_method, collection_method}:
            raise ValidationError('Toggling between managed and non-managed is not '
                                  'possible at the moment.')

        if collection_method != 'automatic':
            return collection_method
        if not payment_method:
            raise ValidationError('Automatic payment requires a payment method.')
        return collection_method


class OrderAdminForm(StateMachineMixin, PaymentMethodLimitMixin, forms.ModelForm):
    class Meta:
        model = models.Order
        exclude = ['id']


class AdminTransactionRefundForm(forms.ModelForm):
    class Meta:
        model = models.Order
        exclude = ['id']

    refund_amount = form_fields.MoneyFormField(
        required=False,
        help_text='Amount to refund.')

    log = log.getChild('AdminTransactionRefundForm')

    def clean_refund_amount(self):
        refund_in_cents = self.cleaned_data['refund_amount']
        refund = money.Money(self.instance.currency, refund_in_cents)

        if not refund:
            # No refund is fine.
            return

        refundable = self.instance.refundable
        if refund > refundable:
            raise ValidationError(
                f'Cannot refund more than {refundable.with_currency_symbol()}')
        if refund.cents < 0:
            raise ValidationError(f'Cannot refund negative amounts')
        return refund

    def save(self, commit=True):
        """Save the model and process the refund if successful."""
        instance: models.Transaction = super().save(commit=commit)
        refund: money.Money = self.cleaned_data['refund_amount']
        if not refund:
            self.log.debug('Not processing empty refund for transaction pk=%r', self.instance.pk)
            return instance

        self.log.debug('Processing refund of %s for transaction pk=%r', refund, self.instance.pk)
        try:
            instance.refund(refund)
        except exceptions.GatewayError as ex:
            self.log.exception('Error refunding %s for transaction pk=%r: %s',
                               refund, self.instance.pk, ex)
            raise ValidationError(f'The refund could not be processed: {ex}')

        return instance


class EmailRequiredMixin:
    cleaned_data: dict
    instance: User

    def clean_email(self) -> str:
        if self.cleaned_data['email']:
            return self.cleaned_data['email']

        try:
            if self.instance.customer and self.instance.customer.billing_email:
                # If the user has no email but it does have a billing email,
                # just use that instead.
                return self.instance.customer.billing_email
        except models.Customer.DoesNotExist:
            pass

        from django.core.exceptions import ValidationError
        raise ValidationError('Every user should have an email address')


class AdminUserChangeForm(EmailRequiredMixin, auth_forms.UserChangeForm):
    pass


class AdminUserCreationForm(EmailRequiredMixin, auth_forms.UserCreationForm):
    pass

templates/settings/billing_address.html
{% extends "settings/base.html" %}
{% block content_settings %}
{{ block.super }}
<h2 class="mt-2 text-secondary">Billing Address</h2>
<form class="p-3" id="billing-address-form" method="post">
  <ul class="form">
    {% csrf_token %}
    {{ form.as_ul }}
  </ul>
  <hr/>
  <button class="btn btn-success px-5 mt-3" id="submit-billing-info" type="submit"><i class="fa fa-check"></i>Save Changes</button>
</form>{% endblock content_settings %}

templates/settings/extend_membership.html
{% extends "settings/membership_base.html" %}
{% block after_membership_info %}
<h2>Extend your Membership</h2>
<p>
  Here you can pay any amount you want to extend your membership. Your current membership
  level <strong>{{ membership.level.name }}</strong> equates to
  <strong>{{ price_per_month.with_currency_symbol }}&nbsp;per&nbsp;month</strong>.
  
</p>
<p>Currently your membership will want renewing on {{ subscription.next_payment|date }}.</p>
<p id="nothing_entered_text">Enter any amount to compute the new renewal date.</p>
<p id="new_date_text" style="display: none">The new renewal date<sup>*</sup> will be <strong><span id="new_renewal_date">TBD</span></strong>
</p>
<form class="checkout-form pt-3" id="payment-form" method="post">{% csrf_token %}
  <section class="checkout-form-fields">
    <ul class="form">{{ form.as_ul }}</ul>
    <div id="gateway-errors"></div>
  </section>
  <hr/>
  <button class="btn btn-filled-success w-100" id="submit_button" type="submit"><i class="fa fa-check"></i><span id="submit_button_text">Pay Any Amount</span></button>
</form>
<p><small><sup>*</sup>The actual renewal date may differ from the precalculated date by a day, owing to
    timezone differences, time between this calculation and the actual payment coming through,
    etc.</small></p>{% if subscription.collection_method == 'automatic' %}
<p><small><sup>**</sup>Paying here does not change the payment method associated with your membership.
    Future automatic payments will be charged to your
    {{ subscription.payment_method.recognisable_name }} regardless of how you pay here.</small></p>{% endif %}
{% endblock %}
{% block footer_scripts %}
<script src="https://js.braintreegateway.com/web/dropin/1.13.0/js/dropin.min.js"></script>
<script>
  let price_per_day = {{ price_per_day.decimals_string }};
  let price_per_month = {{ price_per_month.decimals_string }};
  let next_payment = new Date("{{ subscription.next_payment.isoformat }}");
  
  function compute_renewal() {
  	let amount_as_str = $('#id_price').val();
  	let amount_as_decimal = parseFloat(amount_as_str);
  
  	// NaN is weird in that (x != x) is true for x=NaN.
  	if (typeof amount_as_decimal != 'number' || amount_as_decimal != amount_as_decimal) {
  		// Not a float or integer.
  		$('#submit_button').attr('disabled', 'disabled').removeClass('btn-success');
  		$('#new_date_text').hide();
  		$('#nothing_entered_text').show();
  		return;
  	}
  
  	// Compute the next date based on the price per month.
  	let nr_of_months = amount_as_decimal / price_per_month;
  	let whole_months = Math.floor(nr_of_months);
  	let nr_of_days = (nr_of_months - whole_months) * 30.4;
  	let new_next_payment = new Date(next_payment);
  	new_next_payment.setMonth(new_next_payment.getMonth() + whole_months);
  	new_next_payment.setDate(next_payment.getDate() + nr_of_days);
  	// console.log({
  	// 	amount_as_str: amount_as_str,
  	// 	amount_as_decimal: amount_as_decimal,
  	// 	nr_of_days: nr_of_days,
  	// 	price_per_day: price_per_day,
  	// 	next_payment: next_payment,
  	// 	new_next_payment: new_next_payment,
  	// });
  
  	// Shovel everything into the DOM.
  	$('#new_renewal_date').text(
  		new_next_payment.toLocaleDateString('en',
  		 {weekday: 'long', month: 'long', year: 'numeric', day: 'numeric'}));
  
  	$('#nothing_entered_text').hide();
  	$('#new_renewal_date').show();
  	$('#new_date_text').show();
  	$('#submit_button_text').text('Pay {{ price_per_month.currency_symbol }}' + amount_as_str);
  }
  
  $('#id_price').on('change', compute_renewal);
  $('#id_price').on('keyup', compute_renewal);
  compute_renewal();
  
  let client_token = '{{ client_token }}';
  $("div[data-gateway-name='braintree']").braintree_gateway_group(
  	'#submit_button', '#gateway-errors',
  	'#id_payment_method_nonce', client_token);
  
</script>{% endblock %}

templates/settings/extend_membership_done.html
{% extends "settings/membership_base.html" %}
{% block after_membership_info %}
<h2>Extend your Membership</h2>
<p>
  Your {{ membership.level.name }} membership has been extended to
  {{ subscription.next_payment|date }}.
  
</p>
<p><a class="btn btn-success" href="{% url 'settings_membership_edit' membership_id=membership_id  %}">Finish</a></p>{% endblock after_membership_info %}

templates/settings/home.html
{% extends "settings/base.html" %}
{% load humanize %}
{% load wagtailcore_tags %}
{% block content_settings %}
{{ block.super }}
<h2 class="mt-2 text-secondary">Memberships</h2>{% if memberships %}
<table class="table table-striped m-3">
  {% regroup memberships by status as memb_by_status %}
  {% for status, membs in memb_by_status %}
  <tr class="status-header membership-{{ status }}">
    <th colspan="3">
      <h4 class="m-0">{{ status.title }}</h4>
    </th>
  </tr>{% for m in membs %}
  <tr class="membership-{{ status }}">
    <td><a href="{% url 'settings_membership_edit' m.id %}">{{ m.level }}</a></td>
    <td><a class="text-muted" href="{% url 'settings_membership_edit' m.id %}">{{ m.display_name }}</a></td>
    <td><a class="text-muted" href="{% url 'settings_membership_edit' m.id %}">{{ m.created_at | naturaltime }}</a></td>
  </tr>{% endfor %}
  {% endfor %}
</table>{% else %}
<div class="pt-2">
  <p>You do not have a Blender Development Fund membership yet.</p>
  <p><a class="btn btn-filled-success px-5" href="{% slugurl 'home' %}#join"><i class="fa fa-heart"></i>Subscribe Now</a></p>
</div>{% endif %}
{% endblock content_settings %}

templates/settings/membership_base.html
{% extends "settings/base.html" %}
{% load humanize %}
{% block content_settings %}
{{ block.super }}
<h2 class="mt-2 text-secondary">
  Membership
  {% if user.is_staff and perms.blender_fund_main.change_membership %}<a href="{% url 'admin:blender_fund_main_membership_change' object_id=membership.pk %}">(edit)</a>{% endif %}
</h2>
<div class="row">
  <div class="{% if membership.level.badge %}col-md-9{% else %}col-md-12{% endif %}">
    <p class="lead">Your <strong>{{ membership.level.name }}</strong> membership started	<abbr title="{{ membership.created_at }}">{{ membership.created_at | naturaltime }}</abbr>
      and is currently {{ membership.status }}.
      
    </p>
  </div>{% if membership.level.badge %}
  <div class="col-md-3"><img class="img-responsive" src="{{ membership.level.badge.url }}"/></div>{% endif %}
</div>{% block after_membership_info %}{% endblock %}
{% endblock content_settings %}

templates/settings/membership_cancel.html
{% extends "settings/membership_base.html" %}
{% block after_membership_info %}
<h2>Cancellation</h2>
<p>Are you sure you want to cancel your Blender Development Fund membership?</p>{% if subscription.status == 'active' and subscription.next_payment_in_future %}
<p>
  Your membership will remain active until {{ subscription.next_payment|date }}, since you have
  paid for your membership until then.
</p>{% endif %}
<form class="form" method="post">
  {% csrf_token %}
  {{ form.as_ul }}
  <hr/><a class="btn" href="{% url 'settings_membership_edit' membership_id=membership.id %}"><span>← Keep Membership and Go Back</span></a>
  <button class="btn-danger form-submit" id="submit-button" type="submit"><span>Confirm Cancellation of Membership</span></button>
</form>{% endblock after_membership_info %}

templates/settings/membership_edit.html
{% extends "settings/membership_base.html" %}
{% load looper %}
{% load humanize %}
{% block after_membership_info %}
{% if subscription.status %}
<hr/>{% if subscription.next_payment %}
  {% if subscription.status == 'active' or subscription.status == 'on-hold' %}
    {% if subscription.next_payment_in_future %}
<p>
  The next {{ subscription.collection_method }} charge of  {{ subscription | pricing }}
  will be <abbr title="{{ subscription.next_payment }}">{{ subscription.next_payment | naturaltime }}</abbr>.
</p>    {% else %}
<p>
  The last {{ subscription.collection_method }} charge of {{ subscription | pricing }}
  was due <abbr title="{{ subscription.next_payment }}">{{ subscription.next_payment | naturaltime }}</abbr>.
</p>    {% endif %}
  {% elif subscription.status == 'pending-cancellation' %}
<p>Your membership is pending cancellation. It will be deactivated <abbr title="{{ subscription.next_payment }}">{{ subscription.next_payment | naturaltime }}</abbr>.</p>  {% endif %}
{% endif %}
{% if not membership.is_managed %}
{% with subscription.payment_method as pay_meth %}
<p>
  {% if not pay_meth %}
  Payment method: Unknown
  {% elif pay_meth.is_deleted %}
  Payment method: The payment method previously used for this membership was removed.
  {% else %}
  Your payment method is: {{ pay_meth.recognisable_name }}
  {% endif %}
  {% if subscription %}<small>(<a href="{% url 'looper:payment_method_change' subscription_id=subscription.id %}">change</a>)</small>{% endif %}
</p>{% endwith %}
{% if subscription.status == 'on-hold' %}
<p><a class="btn btn-filled-success px-5" href="{% url 'looper:checkout_existing_order' order_id=order.pk %}"><i class="fa fa-check"></i>Pay Membership</a></p>{% endif %}
{% endif %}
{% if user.is_staff and perms.looper.change_subscription %}
<div class="bg-light p-3 m-3 rounded border" title="For admin eyes only">
  <h4 class="m-0 pb-2">Admin Tools</h4>
  <ul>
    <li><a class="font-weight-bold" href="{% url 'admin:looper_subscription_change' object_id=subscription.pk %}" title="Edit in Admin">Subscription</a><span class="text-secondary pl-2">#{{ subscription.id }} ({{ subscription.status }})</span></li>{% if order %}
    <li><a class="font-weight-bold" href="{% url 'admin:looper_order_change' object_id=order.pk %}" title="Edit order in Admin">Order</a><span class="text-secondary pl-2">#{{ order.pk }} ({{ order.status }})</span></li>{% endif %}
    {% if transaction %}
    <li><a class="font-weight-bold" href="{% url 'admin:looper_transaction_change' object_id=transaction.pk %}" title="Edit transaction in Admin">Transaction</a><span class="text-secondary pl-2">#{{ transaction.pk }} ({{ transaction.status }})</span></li>{% endif %}
  </ul>
</div>{% endif %}
{% endif %}
{% if subscription and subscription.collection_method == 'automatic' and 'cancel' not in subscription.status %}
<hr/>
<h3>Automatic Payment</h3>{% if order %}
    {% if order.status == 'created' %}
    {% elif order.status == 'soft-failed' %}
<p>
  Automatic payment failed on {{ transaction.recorded_at }}, but we will automatically try again
  soon. We have made {{ order.collection_attempts }} of a maximum of
  {{ settings.LOOPER_CLOCK_MAX_AUTO_ATTEMPTS }} collection attemps. In the mean time, your
  membership will remain active.
</p>
<p>The last error we received was: <span class="transaction-error">{{ transaction.failure_message }}</span></p>    {% elif order.status == 'failed' %}
<p>
  Automatic payment failed multiple times, even after trying
  {{ order.collection_attempts }} times. As a result, your membership
  has been deactivated.
</p>
<p>The error we received was: <span class="transaction-error">{{ transaction.failure_message }}</span></p>    {% elif order.status == 'paid' or order.status == 'fulfilled' %}
<p><i class="fa fa-check-circle text-success px-2"></i> Payment was successful <abbr title="{{ transaction.created_at }}">{{ transaction.created_at | naturaltime }}</abbr>.</p>    {% elif order.status == 'cancelled' %}
<p>Automatic payment cancelled and will not be retried.</p>    {% endif %}
{% endif %}
{% if subscription.next_payment %}
<p>The next automatic payment is scheduled for {{ subscription.next_payment }}.</p>{% else %}
<p>
  There is no next automatic payment scheduled. Please contact
  <a href="mailto:{{ settings.ADMIN_MAIL }}?subject=No next payment for membership {{ membership.id }}">{{ settings.ADMIN_MAIL }}</a> about this.
</p>{% endif %}
{% endif %}
{% if may_be_charged %}
<h3>Extend your Membership</h3>
<p>You can arbitrarily extend your membership by paying any amount. <a href="{% url 'membership_extend' membership_id=membership.id %}">Extend my membership now!</a></p>{% endif %}
{% if subscription and subscription.status == 'cancelled' %}
<h3>Membership Cancelled</h3>
<p>This membership has been cancelled. :(</p>{% else %}
<hr/>
<h3>Public Information</h3>{% if membership.level.visible_attributes_list %}
<p>Show off! Fill in your/your company info to be displayed in the Sponsors section of the Development Fund frontpage.</p>{% else %}
<p>Your subscription does not have public attributes. Consider upgrading to get your name, a link to your website, or your logo out there!</p>{% endif %}
<form class="checkout-form p-3" id="payment-form" method="post" enctype="multipart/form-data" action="{% url 'settings_membership_edit' membership.id %}">
  <ul class="form">
    {% csrf_token %}
    {{ form.as_ul }}
  </ul>
  <div class="clearfix"></div>{% if membership.level.bid_badge_name %}
  <p>You can view your membership badge in your <a href="{{ settings.BLENDER_ID.BASE_URL }}">Blender ID Profile</a>.
    For your badge to show up on other websites may take some time (less than a day), and may require you to log in at that site again.
  </p>{% endif %}
  <div class="d-flex align-items-center pt-3">
    <button class="btn btn-success px-5" id="submit-button" type="submit"><i class="fa fa-check"></i>Save Changes</button>{% if subscription.status != 'pending-cancellation' and subscription.status != 'cancelled' %}<a class="ml-auto text-danger" href="{% url 'settings_membership_cancel' membership_id=membership.id %}"><span>Cancel Membership</span></a>{% endif %}
  </div>
</form>{% endif %}
{% endblock after_membership_info %}

templates/settings/payment_method_change.html
{% extends "settings/base.html" %}
{% block content_settings %}
{{ block.super }}
<h2 class="mt-2 text-secondary">
  Change Payment Method
  
</h2>
<p>Your <strong>{{ subscription.plan.name }} {{ subscription.plan.product.name }}</strong> is currently using
  <strong>{{ current_payment_method.recognisable_name }}</strong> as payment method.
  
  Feel free to change it below.
  
</p>
<div class="m-3">
  <form class="form" id="payment-method-change-form" method="post">{% csrf_token %}
    <section class="checkout-form-fields pt-4">
      <ul class="form">{{ form.as_ul }}</ul>
      <div id="gateway-errors"></div>
    </section>
    <hr/>
    <div class="d-flex align-items-center pt-3"><a class="p-3" href="{% url 'settings_home' %}">Cancel</a>
      <button class="ml-auto btn-success form-submit px-5" id="change_payment_method_button" type="submit"><i class="fa fa-check"></i>Switch Payment method</button>
    </div>
  </form>
</div>{% endblock content_settings %}
{% block footer_scripts%}
<script src="https://js.braintreegateway.com/web/dropin/1.13.0/js/dropin.min.js"></script>
<script>
  let client_token = '{{ client_token }}';
  $("div[data-gateway-name='braintree']").braintree_gateway_group(
  	'#change_payment_method_button', '#gateway-errors',
  	'#id_payment_method_nonce', client_token);
  
</script>{% endblock footer_scripts%}

templates/settings/payment_method_delete.html
{% extends "settings/base.html" %}
{% block content_settings %}
<h2 class="mt-2 text-secondary">Payment Methods</h2>
<form method="post">{% csrf_token %}
  <p>Are you sure you want to delete payment method "{{ object }}"?</p>
  <p class="pt-3">
    <input class="btn btn-filled-danger px-5" type="submit" value="Confirm Deletion"/><a class="pl-3" href="{% url 'looper:payment_methods' %}">Cancel</a>
  </p>
</form>{% endblock content_settings %}

templates/settings/payment_methods.html
{% extends "settings/base.html" %}
{% block head %}
<style>
  td.actions a {
  	padding: 1mm 2mm;
  }
</style>{% endblock %}
{% block content_settings %}
<h2 class="mt-2 text-secondary">Payment Methods</h2>
<p class="pb-3">
  Here you can replace and delete payment methods. You can add a new one while replacing an old
  one, or while paying for something.
  
</p>
<table class="table table-striped box m-3">
  <tbody>
    {% for payment_method in object_list %}
    {% with payment_method.gateway_properties as pm_props %}
    <tr>{% if pm_props is None %}
      <td>
        Invalid payment method; just delete this one. This can happen when
        the payment method was deleted at the payment service provider.
      </td>{% else %}
      <td><img class="img-responsive" src="{{ pm_props.image_url }}"/></td>{% if payment_method.method_type == 'cc' %}
      <td>{{ pm_props.card_type }}</td>
      <td>Ending with <strong>{{ pm_props.last_4 }}</strong></td>
      <td>Expires <strong>{{ pm_props.expiration_date }}</strong></td>{% elif payment_method.method_type == 'paypal_account'%}
      <td colspan="3">With email <strong>{{ pm_props.email }}</strong></td>{% else %}
      <td colspan="3">{{ pm_props.recognisable_name }}</td>{% endif %}
      {% endif %}
      <td class="actions"><a href="{% url 'looper:payment_method_replace' pk=payment_method.pk %}">Replace</a><a class="text-danger" href="{% url 'looper:payment_method_delete' pk=payment_method.pk %}">Remove</a></td>
    </tr>{% endwith %}
    {% endfor %}
  </tbody>
</table>{% endblock content_settings %}