looper/urls.py
from django.urls import path

from .views import checkout, settings, preferred_currency

app_name = 'looper'
urlpatterns = [
    path('checkout/<int:plan_id>',
         checkout.ChooseDefaultPlanVariationView.as_view(), name='checkout_new'),
    path('checkout/<int:plan_id>/choose/<int:current_plan_variation_id>',
         checkout.ChoosePlanVariationView.as_view(), name='checkout_choose_plan_variation'),
    path('checkout/<int:plan_id>/variation/<int:plan_variation_id>',
         checkout.CheckoutView.as_view(), name='checkout'),
    path('checkout/pay/<int:order_id>',
         checkout.CheckoutExistingOrderView.as_view(), name='checkout_existing_order'),
    path('checkout/done/<int:transaction_id>', checkout.DoneView.as_view(), name='checkout_done'),
    path('checkout/<gateway_name>/<int:pk>',
         checkout.TransactionlessCheckoutDoneView.as_view(),
         name='transactionless_checkout_done'),

    path('settings/billing/', settings.BillingAddressView.as_view(), name='settings_billing_info'),
    path('settings/personal/', settings.PersonalInfoView.as_view(), name='settings_personal_info'),
    path('settings/billing/payment-methods/',
         settings.PaymentMethodsView.as_view(),
         name='payment_methods'),
    path('settings/billing/payment-methods/change/<int:subscription_id>',
         settings.PaymentMethodChangeView.as_view(),
         name='payment_method_change'),
    path('settings/billing/payment-methods/replace/<int:pk>',
         settings.PaymentMethodReplaceView.as_view(),
         name='payment_method_replace'),
    path('settings/billing/payment-methods/delete/<int:pk>',
         settings.PaymentMethodDeleteView.as_view(),
         name='payment_method_delete'),

    # Note: this URL is used hardcodedly in websrc/scripts/tutti/02_currency.js
    path('preferred-currency', preferred_currency.CurrencySelectorView.as_view(),
         name='preferred_currency'),
]

looper/forms.py
import logging
import typing

from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
import django.contrib.auth.forms as auth_forms

from . import exceptions, models, model_mixins, money, form_fields

log = logging.getLogger(__name__)


class BlenderClassesFormMixin:
    """Adds the CSS classes we need to Django forms."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = f'field-{field_name}'

    def __getitem__(self, field_name: str):
        """Ugly hack to get custom CSS classes in the row container element.

        This will break when Django changes its internal structure.
        """
        from django.forms import BoundField

        # BaseForm._html_output() uses `self[field_name]` to obtain the bound field.
        # To hook into that. we override __getitem__().
        bound_field = super().__getitem__(field_name)  # type: ignore
        if not isinstance(bound_field, BoundField):
            return bound_field

        # `bound_field.css_classes()` is used by BaseForm._html_output() to obtain the
        # CSS classes that are used by the <li> element (when using form.as_ul()).
        # Fortunately it accepts extra CSS classes, but unfortunately we cannot pass
        # anything to the call. Instead, we replace that function with our own, and
        # inject the extra classes there.
        orig_css_classes = bound_field.css_classes

        def css_classes(extra_class: typing.Optional[str] = None) -> str:
            widget_classes: str = bound_field.field.widget.attrs.get('class', '')
            if extra_class:
                widget_classes = f'{widget_classes} {extra_class}'
            return orig_css_classes(widget_classes)

        bound_field.css_classes = css_classes
        return bound_field


class AddressForm(BlenderClassesFormMixin, forms.ModelForm):
    class Meta:
        model = models.Address
        exclude = ['category', 'user']


class BasePaymentForm(forms.Form):
    payment_method_nonce = forms.CharField(initial='set-in-javascript', widget=forms.HiddenInput())
    gateway = form_fields.GatewayChoiceField()


class BaseCheckoutForm(BasePaymentForm):
    # These are used when a payment fails, so that the next attempt to pay can reuse
    # the already-created subscription and order.
    subscription_pk = forms.CharField(widget=forms.HiddenInput(), required=False)
    order_pk = forms.CharField(widget=forms.HiddenInput(), required=False)


class CheckoutForm(BaseCheckoutForm, AddressForm):
    class Meta(AddressForm.Meta):
        pass


class PaymentMethodReplaceForm(BasePaymentForm):
    pass


class ChangePaymentMethodForm(BasePaymentForm):
    next_url_after_done = forms.CharField(widget=forms.HiddenInput())


class CustomerForm(BlenderClassesFormMixin, forms.ModelForm):
    class Meta:
        model = models.Customer
        exclude = ['user', 'vat_number', 'tax_exempt']


class StateMachineMixin(forms.ModelForm):
    """Mix-in for forms that handle looper.model_mixins.StateMachineMixin objects."""

    def clean_status(self):
        assert isinstance(self.instance, model_mixins.StateMachineMixin)

        old_status = self.instance.status
        new_status = self.cleaned_data['status']
        if old_status == new_status:
            # Always accept the current status.
            return new_status

        if not self.instance.may_transition_to(new_status):
            raise ValidationError(f'Status transition {old_status.title()} → '
                                  f'{new_status.title()} is not allowed.')
        return new_status


class PaymentMethodLimitMixin(forms.ModelForm):

    def __init__(self, *args, instance: typing.Optional[models.Subscription] = None, **kwargs) \
            -> None:
        if not instance:
            # When there is no instance, we don't know whose payment methods to list,
            # so it's better to not list them at all.
            invalid_user_id = -1
            queryset = models.PaymentMethod.objects.filter(user_id=invalid_user_id)
        else:
            queryset = instance.user.paymentmethod_set
        self.base_fields['payment_method'].queryset = queryset
        super().__init__(*args, instance=instance, **kwargs)


class SubscriptionAdminForm(StateMachineMixin, PaymentMethodLimitMixin, forms.ModelForm):
    class Meta:
        model = models.Subscription
        exclude = ['id']

    def clean_collection_method(self) -> str:
        payment_method = self.cleaned_data['payment_method']
        collection_method = self.cleaned_data['collection_method']

        if self.instance.collection_method != collection_method and \
                'managed' in {self.instance.collection_method, collection_method}:
            raise ValidationError('Toggling between managed and non-managed is not '
                                  'possible at the moment.')

        if collection_method != 'automatic':
            return collection_method
        if not payment_method:
            raise ValidationError('Automatic payment requires a payment method.')
        return collection_method


class OrderAdminForm(StateMachineMixin, PaymentMethodLimitMixin, forms.ModelForm):
    class Meta:
        model = models.Order
        exclude = ['id']


class AdminTransactionRefundForm(forms.ModelForm):
    class Meta:
        model = models.Order
        exclude = ['id']

    refund_amount = form_fields.MoneyFormField(
        required=False,
        help_text='Amount to refund.')

    log = log.getChild('AdminTransactionRefundForm')

    def clean_refund_amount(self):
        refund_in_cents = self.cleaned_data['refund_amount']
        refund = money.Money(self.instance.currency, refund_in_cents)

        if not refund:
            # No refund is fine.
            return

        refundable = self.instance.refundable
        if refund > refundable:
            raise ValidationError(
                f'Cannot refund more than {refundable.with_currency_symbol()}')
        if refund.cents < 0:
            raise ValidationError(f'Cannot refund negative amounts')
        return refund

    def save(self, commit=True):
        """Save the model and process the refund if successful."""
        instance: models.Transaction = super().save(commit=commit)
        refund: money.Money = self.cleaned_data['refund_amount']
        if not refund:
            self.log.debug('Not processing empty refund for transaction pk=%r', self.instance.pk)
            return instance

        self.log.debug('Processing refund of %s for transaction pk=%r', refund, self.instance.pk)
        try:
            instance.refund(refund)
        except exceptions.GatewayError as ex:
            self.log.exception('Error refunding %s for transaction pk=%r: %s',
                               refund, self.instance.pk, ex)
            raise ValidationError(f'The refund could not be processed: {ex}')

        return instance


class EmailRequiredMixin:
    cleaned_data: dict
    instance: User

    def clean_email(self) -> str:
        if self.cleaned_data['email']:
            return self.cleaned_data['email']

        try:
            if self.instance.customer and self.instance.customer.billing_email:
                # If the user has no email but it does have a billing email,
                # just use that instead.
                return self.instance.customer.billing_email
        except models.Customer.DoesNotExist:
            pass

        from django.core.exceptions import ValidationError
        raise ValidationError('Every user should have an email address')


class AdminUserChangeForm(EmailRequiredMixin, auth_forms.UserChangeForm):
    pass


class AdminUserCreationForm(EmailRequiredMixin, auth_forms.UserCreationForm):
    pass

templates/checkout/checkout.html
{% extends "checkout/checkout_base.html" %}
{% load looper %}
{% block head %}
{% load static %}
<script src="{% static 'js/vendor/select2.min.js' %}"></script>{% endblock %}
{% block after_header %}
<form class="checkout-form pt-3" id="payment-form" method="post">{% csrf_token %}
  <section class="checkout-form-fields">
    <ul class="form">{{ form.as_ul }}</ul>
    <div id="gateway-errors"></div>
  </section>
  <hr/>
  <button class="btn btn-filled-success w-100" id="submit_button" type="submit"><i class="fa fa-check"></i>Subscribe</button>
</form>{% endblock %}
{% block footer_scripts %}
<script src="https://js.braintreegateway.com/web/dropin/1.13.0/js/dropin.min.js"></script>
<script>
  let client_token = '{{ client_token }}';
  
  $("div[data-gateway-name='braintree']").braintree_gateway_group(
  	'#submit_button', '#gateway-errors',
  	'#id_payment_method_nonce', client_token);
  
  //- Initialize the nicer country picker.
  $('#id_country').select2();
  
  //- Append the '.field-more-fields' button after the Full Name.
  $('.field-full_name').append('\
  	<small class="field-more-fields js-show-full-form" title="You can set your billing information later">\
  		Billing Address <i class="fa fa-angle-down"></i> \
  	</small>');
  
  //- Display all fields.
  $('body').on('click', '.js-show-full-form', function(){
  	$(this).toggleClass('active');
  	let fieldsToShow = 'li.field-region, li.field-locality, li.field-company, li.field-country, li.field-postal_code, li.field-billing_email, li.field-street_address';
  	$(fieldsToShow).toggleClass('show');
  });
  
  //- Append the '.field-more-billing_address' button to the street_address field.
  $('.field-street_address').append('\
  	<div class="field-more-billing_address js-show-extended_address" title="Toggle extended address">\
  		<i class="fa fa-plus"></i>\
  	</div>');
  
  //- Display extended address field.
  $('body').on('click', '.js-show-extended_address', function(){
  	$(this).toggleClass('active');
  	$('li.field-extended_address').toggleClass('show');
  });
</script>{% endblock %}

templates/checkout/checkout_anonymous.html
{% extends "checkout/checkout_base.html" %}
{% block after_header %}
<p>
  To see your payment options, please sign in with your Blender ID account. If you don't
  have such an account, you can register for free.
</p>
<p style="margin-top: 1cm; text-align: right"><a class="btn btn-success" href="{{ settings.LOGIN_URL }}">Sign in/up with Blender ID</a></p>{% endblock %}

templates/checkout/checkout_base.html
{% extends "blender_fund/empty_page.html" %}
{% load looper %}
{% block content %}
<div class="checkout-container">
  <section class="checkout">
    <header>
      <div class="d-flex justify-content-between"><a class="text-muted" href="/"><i class="fa fa-angle-left pr-3"></i> Blender Development Fund</a><a title="Change plan" href="{% url 'looper:checkout_choose_plan_variation' plan_id=plan.id current_plan_variation_id=plan_variation.id %}">Plan variations available</a></div>
      <section class="plan-info d-flex align-items-center">
        <h2 class="my-0 pt-4">{{ plan.description }}</h2>
        <h2 class="ml-auto text-secondary my-0 pt-4"><a title="Change plan" href="{% url 'looper:checkout_choose_plan_variation' plan_id=plan.id current_plan_variation_id=plan_variation.id %}"><span>{{ plan_variation|pricing }}</span></a></h2>
      </section>
    </header>
    <hr/>{% block after_header %}{% endblock %}
  </section>
</div>{% endblock %}

templates/checkout/checkout_done.html
{% extends "blender_fund/empty_page.html" %}
{% block head %}
<style>
  .notes {
      margin-top: 4em;
      margin-left: auto;
      margin-right: auto;
      width: 30em;
      color: #ddd;
      font-size: smaller;
  }
</style>{% endblock %}
{% block content %}
<div class="checkout-yay-bg py-5 checkout-container">
  <div class="container text-center py-5">
    <h1 class="thanks">Thank you {{ user.customer.full_name }}! <i class="fa fa-heart text-danger pl-3"></i></h1>
    <div class="lead pt-4">You are now a <strong>{{ order.subscription.plan }}</strong> member of the Blender Development Fund</div>
    <div class="checkout-yay py-3">{% with membership=order.subscription.membership %}<a class="plan" href="{% url 'settings_membership_edit' membership_id=membership.pk %}" title="Manage your memberships">{% if membership.level.badge %}<img class="img-responsive" src="{{ membership.level.badge.url }}" alt="{{ order.subscription.plan }}"/>{% else %}<span>
          <h1>{{ order.subscription.plan }}</h1></span>{% endif %}</a><a class="d-block pt-5" href="{% url 'settings_membership_edit' membership_id=membership.pk %}" title="Manage your memberships">Manage your membership<i class="fa fa-angle-right pl-2"></i></a>{% if membership.level.bid_badge_name %}
      <div class="notes">
        <p>You can view your badge in your <a href="{{ settings.BLENDER_ID.BASE_URL }}">Blender ID Profile</a>.
          For your badge to show up on other websites may take some time (less than a day), and may require you to log in at that site again.
        </p>
      </div>{% endif %}
      {% endwith %}
      <canvas class="fireworks"></canvas>
      <div class="background">
        <div class="stars small"></div>
        <div class="stars medium"></div>
        <div class="stars big"></div>
      </div>
    </div>
  </div>
</div>{% endblock %}
{% block footer_scripts %}
<script src="//cdnjs.cloudflare.com/ajax/libs/animejs/2.2.0/anime.min.js"></script>
<script>
  window.human = false;
  
  var canvasEl = document.querySelector('.fireworks');
  var ctx = canvasEl.getContext('2d');
  var numberOfParticules = 50;
  var colors = ['#FFBA08', '#08a7FF', '#FFFFFF'];
  
  function setCanvasSize() {
    canvasEl.width = window.innerWidth;
    canvasEl.height = window.innerHeight;
    canvasEl.style.width = window.innerWidth + 'px';
    canvasEl.style.height = window.innerHeight + 'px';
  }
  
  function setParticuleDirection(p) {
    var angle = anime.random(0, 360) * Math.PI / 180;
    var value = anime.random(50, 180);
    var radius = [-1, 1][anime.random(0, 1)] * value;
    return {
      x: p.x + radius * Math.cos(angle),
      y: p.y + radius * Math.sin(angle)
    }
  }
  
  function createParticule(x,y) {
    var p = {};
    p.x = x;
    p.y = y;
    p.color = colors[anime.random(0, colors.length - 1)];
    p.radius = anime.random(4, 16);
    p.endPos = setParticuleDirection(p);
    p.draw = function() {
      ctx.beginPath();
      ctx.arc(p.x, p.y, p.radius, 0, 2 * Math.PI, true);
      ctx.fillStyle = p.color;
      ctx.fill();
    }
    return p;
  }
  
  function renderParticule(anim) {
    for (var i = 0; i < anim.animatables.length; i++) {
      anim.animatables[i].target.draw();
    }
  }
  
  function animateParticules(x, y) {
    var particules = [];
    for (var i = 0; i < numberOfParticules; i++) {
      particules.push(createParticule(x, y));
    }
    anime.timeline().add({
      targets: particules,
      x: function(p) { return p.endPos.x; },
      y: function(p) { return p.endPos.y; },
      radius: 0,
      duration: anime.random(1200, 6400),
      easing: 'easeOutExpo',
      update: renderParticule
    });
  }
  
  var render = anime({
    duration: Infinity,
    update: function() {
      ctx.clearRect(0, 0, canvasEl.width, canvasEl.height);
    }
  });
  
  var centerX = canvasEl.width / 2;
  var centerY = canvasEl.height / 2;
  
  var centerYPadding = window.innerHeight / 4;
  
  function autoClick() {
    animateParticules(
      anime.random(0, window.innerWidth),
      anime.random(50, window.innerHeight / 3)
    );
    anime({duration: 1200}).finished.then(autoClick);
  }
  
  autoClick();
  setCanvasSize();
  window.addEventListener('resize', setCanvasSize, false);
</script>{% endblock footer_scripts %}

templates/checkout/checkout_done_transactionless.html
{% extends "blender_fund/empty_page.html" %}
{% block head %}
<style>
  .notes {
  	margin-top: 4em;
  	margin-left: auto;
  	margin-right: auto;
  	width: 30em;
  	color: #ddd;
  	font-size: smaller;
  }
  
  .mention, pre {
  	max-width: 60ex;
  	margin-left: auto;
  	margin-right: auto;
  	margin-bottom: 4mm;
  
  	border: thin solid white;
  	border-radius: 1mm;
  	padding: 3mm;
  	color: white;
  }
  .mention {
  	background-color: #000030;
  }
  pre {
  	background-color: transparent;
  	text-align: left;
  }
</style>{% endblock %}
{% block content %}
<div class="checkout-yay-bg py-5 checkout-container">
  <div class="container text-center py-5">
    <h1 class="thanks">Thank you {{ user.customer.full_name }}! <i class="fa fa-heart text-danger pl-3"></i></h1>
    <div class="lead pt-4">You are now a <strong>{{ order.subscription.plan }}</strong> member of the Blender Development Fund</div>
    <p>
      Your membership will be activated as soon as we have handled your bank transfer.
      
    </p>
    <div class="mention">
      <p>
        When paying, mention the following with your bank transfer:
        
      </p>
      <p><strong>Blender Fund Membership subs-{{ order.subscription.id }}</strong></p>
    </div>
    <p>Please send your payment to:</p>
    <p>
      <pre>Stichting Blender Foundation
Buikslotermeerplein 161
1025 ET Amsterdam, the Netherlands

Bank: ING Bank
Bijlmerdreef 109
1102 BW Amsterdam, the Netherlands

BIC/Swift code: INGB NL 2A
IBAN: NL45 INGB 0009356121 (for Euro countries)

Tax number NL 8111.66.223
</pre>
    </p>
    <p>This information is also sent to you by email.</p>{% with membership=order.subscription.membership %}
    <p>Continue to <a href="{% url 'settings_membership_edit' membership_id=membership.id %}">Your Membership</a>.</p>{% if membership.level.bid_badge_name %}
    <div class="notes">
      <p>Once your membership is activated, you can view your badge in your <a href="{{ settings.BLENDER_ID.BASE_URL }}">Blender ID Profile</a>.
        For your badge to show up on other websites may take some time (less than a day), and may require you to log in at that site again.
      </p>
    </div>{% endif %}
    {% endwith %}
  </div>
</div>{% endblock %}

templates/checkout/checkout_existing_order.html
{% extends "blender_fund/empty_page.html" %}
{% load looper %}
{% block content %}
<div class="checkout-container">
  <section class="checkout">
    <header><a class="text-muted" href="/"><i class="fa fa-angle-left pr-3"></i> Blender Development Fund</a>
      <section class="plan-info d-flex align-items-center">
        <h2 class="my-0 pt-4">{{ plan.description }}</h2>
        <h2 class="ml-auto text-secondary my-0 pt-4"><span>{{ order.price.with_currency_symbol }} for {{ subscription.interval_length }} {{ subscription.interval_unit }}</span></h2>
      </section>
    </header>
    <hr/>
    <form class="checkout-form" id="payment-form" method="post">{% csrf_token %}
      <section class="checkout-form-fields">
        <ul class="form">{{ form.as_ul }}</ul>
        <div id="gateway-errors"></div>
      </section>
      <hr/>
      <button class="btn-success form-submit" id="submit_button" type="submit"><span>Pay {{ order.price.with_currency_symbol }}</span></button>
    </form>
  </section>
</div>
<script src="https://js.braintreegateway.com/web/dropin/1.13.0/js/dropin.min.js"></script>
<script>
  let client_token = '{{ client_token }}';
  $("div[data-gateway-name='braintree']").braintree_gateway_group(
  	'#submit_button', '#gateway-errors',
  	'#id_payment_method_nonce', client_token);
  
</script>{% endblock %}

templates/checkout/choose_plan_variation.html
{% extends "blender_fund/empty_page.html" %}
{% load looper %}
{% block content %}
<div class="checkout-container">
  <section class="checkout">
    <header><a class="text-muted" href="/"><i class="fa fa-angle-left pr-3"></i> Blender Development Fund</a>
      <section class="plan-info d-flex align-items-center">
        <h2 class="my-0 pt-4">{{ plan.description }}</h2>
      </section>
    </header>
    <hr/>
    <p>Choose how to subscribe to {{ plan.name }} {{ plan.product.name }}:</p>
    <ul>{% for planvar in object_list %}
      <li><a class="{% if planvar.pk == current_plan_variation.pk %}current{% endif %}" href="{% url 'looper:checkout' plan_id=plan.id plan_variation_id=planvar.id %}">{{ planvar|pricing }}</a>{% if planvar.pk == current_plan_variation.pk %} (currently selected){% endif %}</li>{% empty %}
      <!-- - TODO(fsiddi): Provide link to return to previous page-->
      <p>Sorry, no variation is availale in your currency.</p>{% endfor %}
    </ul>
    <hr class="mt-5"/>
    <p>{% if preferred_currency == 'EUR' %}<a href="javascript:set_preferred_currency('USD');">Switch to $</a>{% else %}<a href="javascript:set_preferred_currency('EUR');">Switch to €</a>{% endif %}</p>
  </section>
</div>{% endblock %}

templates/checkout/not_your_order.html
{% extends "blender_fund/empty_page.html" %}
{% load looper %}
{% block content %}
<div class="checkout-container">
  <section class="checkout">
    <header><a class="text-muted" href="/"><i class="fa fa-angle-left pr-3"></i> Blender Development Fund</a>
      <section class="plan-info d-flex align-items-center">
        <h2 class="my-0 pt-4">Not your payment link</h2>
      </section>
    </header>
    <hr/>
    <p>You seem to have followed someone else's payment link.</p>
  </section>
</div>{% endblock %}